language: go

go:
- 1.1
- 1.2
- 1.3

notificaitons:
  email:
    recipients: virtuallynathan@gmail.com
    on_success: change
    on_failure: always

install:
- go get github.com/virtuallynathan/gosnmp
